import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="bg-gray-100 font-sans min-h-screen">
          <header className="bg-blue-700 text-white p-4">
            <div className="container mx-auto">
              <h1 className="text-2xl font-bold">Indian Pharmaceutical Blog</h1>
              <nav>
                <a className="mr-4" href="#">
                  Home
                </a>
                <a className="mr-4" href="#">
                  About
                </a>
                <a className="mr-4" href="#">
                  Contact
                </a>
              </nav>
            </div>
          </header>
          {children}
          <footer className="bg-blue-800 text-white p-4 mt-8">
            <div className="container mx-auto text-center">
              © 2023 Indian Pharmaceutical Blog
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
